/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicRoutesImport } from './routes/publicRoutes'
import { Route as ProtectedRoutesImport } from './routes/protectedRoutes'

// Create/Update Routes

const PublicRoutesRoute = PublicRoutesImport.update({
  path: '/publicRoutes',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoutesRoute = ProtectedRoutesImport.update({
  path: '/protectedRoutes',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protectedRoutes': {
      id: '/protectedRoutes'
      path: '/protectedRoutes'
      fullPath: '/protectedRoutes'
      preLoaderRoute: typeof ProtectedRoutesImport
      parentRoute: typeof rootRoute
    }
    '/publicRoutes': {
      id: '/publicRoutes'
      path: '/publicRoutes'
      fullPath: '/publicRoutes'
      preLoaderRoute: typeof PublicRoutesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  ProtectedRoutesRoute,
  PublicRoutesRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/protectedRoutes",
        "/publicRoutes"
      ]
    },
    "/protectedRoutes": {
      "filePath": "protectedRoutes.tsx"
    },
    "/publicRoutes": {
      "filePath": "publicRoutes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
